Make\CourtBundle\Entity\CourtCase:
    properties:
        order:
            - NotBlank: ~
        insurerPosition:
            - NotBlank: ~
        caseValue:
            - GreaterThanOrEqual: 0
    constraints:
        - Make\CourtBundle\Validator\Constraints\InsurerPosition: ~
